import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'

import { ThemeProvider } from '../providers/ThemeProvider'
import { MessengerProvider } from '../providers/MessengerProvider'
import '../assets/styles/reset.scss'
import '../assets/styles/globals.scss'
import '../assets/styles/colors.scss'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Messenger',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ThemeProvider>
          <MessengerProvider>
            {children}
          </MessengerProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
